os:
  - windows
  - linux
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"
install: "pip install -r requirements.txt"
script: "coverage run -m unittest discover"
after_success: "coveralls"
